//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_AUTOMATIZACIONEntities : DbContext
    {
        public DB_AUTOMATIZACIONEntities()
            : base("name=DB_AUTOMATIZACIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Familia> Familia { get; set; }
        public virtual DbSet<Propiedades> Propiedades { get; set; }
        public virtual DbSet<TipoItem> TipoItem { get; set; }
        public virtual DbSet<ReglasFamilia> ReglasFamilia { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<Costos> Costos { get; set; }
        public virtual DbSet<ItemCosto> ItemCosto { get; set; }
        public virtual DbSet<ItemDetalle> ItemDetalle { get; set; }
        public virtual DbSet<Item> Item { get; set; }
    
        public virtual ObjectResult<SP_GetItemCostoID_Result> SP_GetItemCostoID(Nullable<int> id_Item)
        {
            var id_ItemParameter = id_Item.HasValue ?
                new ObjectParameter("id_Item", id_Item) :
                new ObjectParameter("id_Item", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetItemCostoID_Result>("SP_GetItemCostoID", id_ItemParameter);
        }
    
        public virtual ObjectResult<SP_GetItemDetalleID_Result1> SP_GetItemDetalleID(Nullable<int> id_Item)
        {
            var id_ItemParameter = id_Item.HasValue ?
                new ObjectParameter("id_Item", id_Item) :
                new ObjectParameter("id_Item", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetItemDetalleID_Result1>("SP_GetItemDetalleID", id_ItemParameter);
        }
    }
}
