//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costos
    {
        public int Id { get; set; }
        public string Categoria { get; set; }
        public string Tipo { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
