//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
[Serializable]
public partial class Familia
{
    public int id { get; set; }
    public string Codigo { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> Estado { get; set; }
    public string Clasificacion { get; set; }
}
