//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    [Serializable]

    public partial class ItemDetalle
    {
        public int Id { get; set; }
        public Nullable<int> IdItem { get; set; }
        public Nullable<int> IdDetalle { get; set; }
        public Nullable<int> Linea { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> CostoUnitario { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> CostoUnitFactor { get; set; }
        public Nullable<decimal> TotalFactor { get; set; }
    }
}
